CREATE TABLE CLIENTES(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	RUA VARCHAR(100) NOT NULL,
	END_NUMERO INT(11) NOT NULL,
	BAIRRO VARCHAR (30) NOT NULL,
	CEP INT(8),
	CPF INT (11) NOT NULL,
	ATIVO BOOLEAN DEFAULT TRUE,
	DATA_CADASTRO DATE DEFAULT NULL
);

INSERT INTO CLIENTES (NOME,RUA,END_NUMERO,BAIRRO,CIDADE,CEP,CPF,DATA_NASC, DATA_CADASTRO)VALUES ('ADMIN', 'RUA TESTE',22,'JARDIM TESTELU','CARAPICUIBA','06000-000','11111111111','1999-12-23',NOW());


INSERT INTO USUARIOS (LOGIN, SENHA, ID_CLIENTES)VALUES ('ADMIN', 'Dan123',1);